" --------------------------------
" vim-plug (auto-install if missing)
" --------------------------------
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()

" --------------------------------
" Theme
" https://draculatheme.com/vim
" --------------------------------
syntax enable
colorscheme dracula
set termguicolors

" --------------------------------
" UI
" --------------------------------
set number                " show line numbers
set mouse=a               " enable mouse in all modes
set nowrap                " don't wrap long lines

" --------------------------------
" Tabs & Indentation
" --------------------------------
set tabstop=4             " a tab = 4 spaces
set shiftwidth=4          " indentation uses 4 spaces
set softtabstop=4         " tab key inserts 4 spaces
set expandtab             " use spaces instead of tabs

set autoindent            " copy indentation from current line
set smartindent           " smarter auto-indentation

" --------------------------------
" fzf
" --------------------------------
nnoremap <C-p> :GFiles<CR>
nnoremap <C-f> :BLines<CR>
nnoremap <leader>f :Rg<CR>
nnoremap <leader>b :Buffers<CR>
